services:
  pokopi-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pokopi_meigen_syu
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true

volumes:
  nuget-cache:
